FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential gcc-multilib

COPY . /fcc
WORKDIR /fcc
RUN make

FROM ubuntu:20.04 as package
COPY --from=builder /fcc/bin/release/fcc /
